services:
  - type: web
    name: telegram-bot-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false # Dashboard မှာ ကိုယ်တိုင်ဖြည့်မယ်
      - key: MMQR_API_SECRET
        sync: false
        
